cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    asap:
      name: asap
      password: $2b$12$b2aXO04GBHQhkMGWguaerOuQpT.cipZMsBbiPV2kIQXKKHXpE/cY6
preauthorized:
  emails:
  - sodyn99@gmail.com
