cookie:
  expiry_days: 1
  key: some_signature_key
  name: streamlit-cookie
credentials:
  usernames:
    asap:
      name: asap
      password: $2b$12$T657ZXBqAyJuartbrwlUMOP9G.n94O8qsdsuyDZRxUKQ2Yj.TsJHu
preauthorized:
  emails:
  - sodyn99@gmail.com
